# To let the CI execute the maven wrapper, use this command and push the change:
#    git update-index --chmod=+x mvnw

sudo: false # route your build to the container-based infrastructure for a faster build
language: java
jdk:
  - openjdk8

env:
  global:
    - secure: "p0k8K9C5/d7rxHLqS28nNNbLCOLDVnFAfJLEVnPFDOpUmE2kXTKfGBoBX5ZhXDuT88MQB4RPXWHUS30ChfnB6LVRyTTT3bsU7vszdgFJROkdVjwnv3YG3V5Q7mCnyoR+Tkujxi0ntr1RypsTFfn19JnRvuJ4MW+8aLk2LUvz6ldBVGU/zP6eomMTHuRsI57Jyd4zfY7YOLFsUBZ3zC+0QQ0MhYcFfWL92mzt0u2fDF45eVJskCi5f3p6FvlSQ8yQ/kYyIuSpFROZEL67H/OhfsBulzCbC0e1I7VD96xdflNDORFV9DF7GN+OogM2Imj1nAZw/cfEnfp47LEduFtNuHWN6g+lG2HkK6aG0RadCjZ0SvA48wtnhN8kg0u7cXCsDnOrWlxKve4VGB+FAHUUm+fJghwfkKMDhKGqC5ulbNk8cgbB2C5xdYzSbC5VpMAugcQs+ogkjfiyQOz5T69uO+JyNTf22LlxOF2YAOctUrQckUN11RfyJfvoTj3jTYwLTR68lDEWszpI2cNqxUuskDc74m9xjFRB0xCTHNUFmcr4DDW09cVyagh9xVmhiUNaNEpH6FUswc3Do5D6CJFnqw2YmahtVrRrLMNZEi0+13w+zAsVhSSNJxt6yYOXXo57SW16Tut+uAL6aoif7hI+GXJzzAyIY7tuIaaQY4RNIec="
    - secure: "wFF2jSRwrb4CbeRR7ujs8Z3IEDBCu/q54xZWgPqtx2QyoVI10Di93dmvJuGzuswTOP9CPgyJ2T/fNFat+EB3eDJ5KnBBOQONXoQjZ7Xjvmwzijt9DNm62RijoIIKcxlrDsLmpXdbR7G+sEFOhdgvGBgdTuPrCDo0Fc0jNCmuN0xypS7fZKlurWdtgBJrRRwwsDbZOPNw/HkMyxZBlqq+FBjRa11DfDruRqTZVGzksnqBbjMVJkEaXRBYeUgm3b9NiILW+5MfhdDxdsukSwM/MT9VlPxJ23CXQ/laJ3TPiMOhJCsdAlciQudijpeYTGw/4jaGFZyvfJ7VYmv+OkV6C3dXo0doLgK+g/1x2AW6q7C/sHEdQ7fq7W+tiGNZSyAXf5O3Kl5ir7q+MqKNuilWd//LUydaIl4EQAs84PD1/FkLOp+9j3LUaPR3ayslw1QZpmAjO9qVzApGlUik8Y06kipEEp6Fcdmj2Rkcf7M0gFIhmfYb+BeSQ+rIFhH4+y2EbSQgG3z3qZQMuFyvOhHop2NKA18g0/qDaUG8tGDdpigzKA6bbTYuYHfYGQzPy1MuSjYutjtBtkfVyvY3tqy+LGofNP+DmM58sgbfi4UWop3pcsGaw4spySluPYV5QWw4ibcxJnREz4JVZgUlHGYD/iWTt1eKLw4n83LpyW1Vl4Q="

before_install:
  - openssl aes-256-cbc -K $encrypted_2715211808bc_key -iv $encrypted_2715211808bc_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./mvnw clean install -Djarsigner.skip=true; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./mvnw clean install -Djarsigner.skip=false; fi'

after_success:
  - ./mvnw test jacoco:report coveralls:report

deploy:
  - provider: script
    script: ./mvnw -s ci-settings.xml deploy -X
    skip_cleanup: true
    on:
      branch: master
      tags: true
  - provider: releases
    api_key:
      secure: "e/QacQA1ue+r7FaVlyR81OOlPSh15nmNZaICF0OoPOXQaJh5+iC/2kXfVivns3thvVAymnUmDYvXLEBydyABue7bF3OxIywj6w0zVmbzLx1yG9WpMzUgnLAGsFkXou7j0HfELWX+t4pyHZuJitEtVqi7pHm/zZ3IpVCwfcm0Rms8LIk9jNlOTc8EUGU7h3K1HPNdm+lru3Pyn+sdHtlxl3Ncu8VpvfvsRMbW1taLZQKAEcfixtevpKmgh+n+bgXfWvTCoVp1p4rZH4Vb9zk6bgw7MeUP6qCErgu9u2z9MlRfFQkIvMCg0Hl5mSruFTAgzhBicLONP+ZUCjrUb2YiS66P3nzucFEYSsBHrkZrhE5K6V1MxW103IqJlvDu6h4HzwuiNqBjZh/qJ0HhrdWe/YA3l+kY/4xaClrEqoHC/WXmY5Pz6IHJ+wbtDJGkCsBcWp5WbrmqfAidlOWGqbNAbHiOeQe3DW1CXkGs62BN+IHclgrjnOQxDRk+hWnRtqDMldaelMXF/t/RhPYU3uMUiFkzDMjFBblGt8nNm+Me3x7kXE3Y52RJBDcxB1Lx86mlx0FeI2ZNo5XvND2Jd7ipUq9DLlWO0rCWukQFw4b9z62ax1453UC7zA6T2QJJORXeuKVuct581c/ltzVju1vrtPt39hcXs91G4B1tMypSLds="
    file_glob: true
    file:
      - "modules/benchmark-jmh/target/benchmark-*-full.jar"
      - "modules/id-mask/target/id-mask-*.jar"
      - "modules/id-mask/target/*.sha256"
      - "modules/id-mask/target/checksum-sha256.txt"
    skip_cleanup: true
    on:
      branch: master
      tags: true

cache:
  directories:
    - $HOME/.m2

notifications:
  slack:
    secure: "A1uEqQZ8i4tFhWJ2HAKCPDBwKHtdkxafK1uavVM2hwPq4EmrbrEuNCbAFdrPk1eZKdbJeDjqc493qWtSRjplxnYYw/0hgmLVcSGk980k1umPV6DUSKAC+rDtXx3yfcsnQtZLQ0DUgE1L+BdiMxwn3Kx2VS4H/eg3WpWK5VhkMs6muiC3ZTIfGUANqaik0mbl4DEHqrnUQTJ00P2K9zy05y+NKGkiQVL4aoKMaLEQ4DG2jZEVATX3T6vYb8SLjqJxVKzJqWboJf0fPFQicLZDw5sLxnYmF+A4IMEWxrYs5FnbkJh7vLMwz7aeCHf/COt9CFwuQj4HBOqjyIP3MGxjh57t3ydqnDorigqETOkQQB3//BFg7DAp0fzdl8qjMMCe+mcJa/DCqPAo1UM8R4uIZ+zJMGGiPW3qTYG0dh8yzBvl6QSCICduh+mCegsF57JcMWTPu0v9SI3PmC4OqMSx51kHOy5vgRvVdRVq1539vYWlWDy0h0tGlouBVSDzjDCSnqVMzEoL7sx4DiTwOoqOiXK9EV3J/jOBhRXsjso/QH6OTIqgx+uQGH5V3S7CL+9BFRePW87JiZy5SKQnVWLvb4nHAEWsSaHMXVmAfYnlbJyUif4AVbWvkdQo2h1BB8whsvIdgbxd+JpRcfqjsxrL5hnp4aeVGLiBD4IX97MX3wY="
  email: false
